import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthModalProvider from "@/components/modals/auth-modal/auth-modal-provider";
import MultiModalProvider from "@/components/modals/multi-modal/multi-modal-provider";
import { Toaster } from "sonner";
import { Provider } from "@radix-ui/react-tooltip";
import Providers from "@/lib/providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Toaster />
          <Provider>
            <AuthModalProvider />
            <MultiModalProvider />
            {children}
          </Provider>
        </Providers>
      </body>
    </html>
  );
}